### ISSUE TITLE
This keeps poping up: AssertionError: regex must capture filename,line,[column,]message

### ISSUE THREAD

**Issue by evandrocoan** [bblanchon/SublimeText-HighlightBuildErrors#24]
```
Running sh D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages/SublimeBuildSystem/Octave.sh sistemas.m
Traceback (most recent call last):
  File "HighlightBuildErrors in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\Highlight Build Errors.sublime-package", line 173, in finish
  File "HighlightBuildErrors in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\Highlight Build Errors.sublime-package", line 155, in doHighlighting
  File "HighlightBuildErrors in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\Highlight Build Errors.sublime-package", line 147, in __init__
AssertionError: regex must capture filename,line,[column,]message
```

**Comment by bblanchon** [comment]
This was supposed to be a hint to help you fix the file_regex in your build system. I admit it was not very clear :sweat_smile: 

Starting with version 3.0.1, it should display the following message:

```
Highlight Build Errors plugin warning: invalid configuration
The regular expression must capture filename,line,[column,]message
Please fix the 'file_regex' in build system configuration.
```

**Comment by evandrocoan** [comment]
Thank you @bblanchon
